name: Deploy Backend API

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'startup.sh'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/ || echo "No tests found"

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create deployment package and deploy
      run: |
        zip -r deploy.zip . -x ".git/*" ".github/*" "*.pyc" "__pycache__/*" "tests/*" ".env" "venv/*" "*.md" "frontend/*" "*.zip"
        az webapp deploy \
          --resource-group rg-sandbox-se-01-p \
          --name app-anthosks-api-se-01-p \
          --src-path deploy.zip \
          --type zip
